name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: Test on PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2']

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@v2

      - name: Run phpunit
        run: vendor/bin/phpunit --verbose

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2']

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@v2

      - name: Run phpstan
        run: vendor/bin/phpstan analyse --no-progress

  codecov:
    name: Upload coverage reports to Codecov
    runs-on: ubuntu-latest

    steps:
      - uses: codecov/codecov-action@v3